accounts/urls.py
from django.urls            import include, path

from .views import Profile

urlpatterns = [
    path("", include('django.contrib.auth.urls')),
    path("profile/",  Profile.as_view(),  name='accounts-profile'),
    path("profile/<username>/",  Profile.as_view(),  name='accounts-profile-byname'),
]

user_requests/urls.py
from django.urls    import path

from .models    import plugin_loader
from .views     import (AvailableRequestsView, RequestConclusionView,
                        RequestDetailView, RequestListView)

app_name = "user_requests"

urlpatterns = [
    path('', AvailableRequestsView.as_view(), name='available'),
    path('list/', RequestListView.as_view(), name='list'),
    path('view/<int:pk>/', RequestDetailView.as_view(), name='review'),
    path('conclusion/', RequestConclusionView.as_view(), name='conclusion'),
] + plugin_loader.urls # Add the URLs for the plugins

userportal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    path(
        'robots.txt',
        TemplateView.as_view(
            template_name="robots.txt", content_type="text/plaintext"
        ), 
        name="robots"
    ),

    path('accounts/',  include('accounts.urls')),
    path('duo/',  include('duo_auth.urls')),
    path('user_requests/',  include('user_requests.urls')),
    path('openacct/',  include('openacct.urls')),
    path('fractalip/',  include('fractalip.urls')),
    path('logins/',  include('admin_toolbelt.contrib.login_records.urls')),
    path('admin/', admin.site.urls),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_requests/models.py
import importlib
import inspect

from django.conf                    import settings
from django.contrib.auth.models     import User
from django.core.mail               import send_mail
from django.db                      import models
from django.template                import Template, Context
from django.urls                    import reverse
from django.utils.module_loading    import import_string


GET_EMAIL_VALUE = getattr(settings, 'USER_REQUESTS_GET_EMAIL',
    lambda u: User.objects.get(username=u).email
)
get_email = (
    GET_EMAIL_VALUE if callable(GET_EMAIL_VALUE) else import_string(GET_EMAIL_VALUE)
)

status_options = (
    ('NEW', 'NEW'),
    ('PENDING', 'PENDING'),
    ('APPROVED', 'APPROVED'),
    ('DECLINED', 'DECLINED'),
    ('PROCESSING', 'PROCESSING'),
    ('PROCESSED', 'PROCESSED'),
    ('FAILED', 'FAILED'),
    ('CANCELLED', 'CANCELLED'),
)


class EmailTemplate(models.Model):
    created         = models.DateTimeField(auto_now_add=True)
    name            = models.CharField(max_length=64)
    default_from    = models.CharField(max_length=64)
    subject         = models.CharField(max_length=64)
    body            = models.TextField()

    def send(self, to, from_email=None, context={}):
        send_mail(
            Template(self.subject).render(Context(context)),
            Template(self.body).render(Context(context)),
            from_email if from_email else self.default_from,
            to,
        )


class Request(models.Model):
    """Common information for all requests, facilitates ListView."""
    submitted       = models.DateTimeField(auto_now_add=True)
    requester       = models.CharField(max_length=32) # request.user.username
    confirmed       = models.BooleanField(blank=True, default=False)
    autoprocess     = models.BooleanField(blank=True, default=True)
    autonotify      = models.BooleanField(blank=True, default=True)
    notification    = models.ForeignKey(
        EmailTemplate, models.SET_DEFAULT, blank=True, null=True, default=1
    )
    description     = models.CharField(max_length=512, blank=True, default="")
    status          = models.CharField(
        max_length=16, choices=status_options, blank=True, default="NEW"
    )

    @classmethod
    def make_from_http_request(cls, request, status='NEW', description=''):
        """Create and save a new request object from an HTTP request."""
        req = cls(requester=request.user.username, status=status, description=description)
        req.save()
        return req

    def review_url(self):
        """Returns the request's review page URL"""
        return reverse('user_requests:review', kwargs={'pk': self.pk})

    def components(self):
        """Returns the components attached to this request"""
        rval = []
        for rt in plugin_loader.request_types:
            rval.extend(rt.objects.filter(request=self))
        return rval

    def on_confirmed(self):
        for comp in self.components():
            comp.on_confirmed()
        self.confirmed = True
        self.save()

    def on_pending(self):
        for comp in self.components():
            comp.on_pending()
        self.status = 'PENDING'
        self.save()

    def on_approved(self):
        for comp in self.components():
            comp.on_approved()

        if self.autoprocess:
            self.on_processed()
        else:
            self.status = 'APPROVED'
            self.save()

    def on_processed(self):
        for comp in self.components():
            comp.on_processed()

        if self.autonotify:
            self.notification.send([get_email(self.requester)], context={'request':self, 'components':self.components()})
        self.status = 'PROCESSED'
        self.save()


class RequestType(models.Model):
    """Abstract Base Class for all Requests"""
    request_visible = True
    request_description = "Set model's request_description to change this text"
    form_view_name = "user_requests:<name>"
    update_view_name = "user_requests:update_<name>"
    widget_template_path = "should_not_exist.html"

    request = models.ForeignKey(Request, on_delete=models.CASCADE)

    @classmethod
    def approved_requests(cls):
        """Get all objects whose request is marked confirmed and approved."""
        return cls.objects.filter(request__status='APPROVED', request__confirmed=True)

    def get_absolute_url(self):
        """Used by the update view to get back to the review page."""
        return self.request.review_url()

    def on_confirmed(self):
        """Abstract method to be defined for a subclass which will be
        called after confirming a request containing this request type.
        """
        pass

    def on_approved(self):
        """Abstract method to be defined for each subclass which will be
        called for each approved request of that type. It is an error to
        not define this method.
        """
        raise NotImplementedError(
            "Subclasses of RequestType must define this method"
        )

    def on_pending(self):
        """Abstract method to be defined for a subclass which will be called
        after a request containing this request type is set to pending.
        """
        pass

    def on_processed(self):
        """Abstract method to be defined for a subclass which will be called
        after a request containing this request type is set to processed.
        """
        pass

    class Meta:
        abstract = True
        app_label = 'user_requests'


class RequestLogEntry(models.Model):
    """Record actions taken by admins on the request."""
    request = models.ForeignKey(Request, on_delete=models.CASCADE)
    logged  = models.DateTimeField(auto_now_add=True)
    text    = models.CharField(max_length=128)

    def __str__(self):
        return '{0} - {1}'.format(self.logged, self.text)


def request_log(request, message):
    RequestLogEntry(request=request, text=message).save()


class RequestPluginLoader():
    def __init__(self):
        self.plugins = list([ 
            importlib.import_module(n) for n in settings.USER_REQUESTS_PLUGINS 
        ])
        self.request_types, self.urls = [], []

        for p in self.plugins:
            self.urls.extend(getattr(p, 'urlpatterns', []))
            self.request_types.extend(getattr(p, 'request_types', []))

plugin_loader = RequestPluginLoader()

user_requests/views.py
from django.conf                    import settings
from django.contrib.auth.mixins     import LoginRequiredMixin, UserPassesTestMixin
from django.http                    import (HttpResponseBadRequest,
                                            HttpResponseForbidden)
from django.shortcuts               import get_object_or_404, redirect, render
from django.urls                    import reverse
from django.utils.module_loading    import import_string
from django.views.generic           import View, ListView, TemplateView
from django.views.generic.edit      import UpdateView

from .models import EmailTemplate, Request, RequestLogEntry, RequestType, request_log


CHECK_ADMIN_VALUE = getattr(settings, 'USER_REQUESTS_CHECK_ADMIN', lambda u: u.is_staff)
check_admin = (
    CHECK_ADMIN_VALUE if callable(CHECK_ADMIN_VALUE) else import_string(CHECK_ADMIN_VALUE)
)


class AvailableRequestsView(LoginRequiredMixin, View):
    """Display the currently available request types"""
    def get(self, request):
        from .models import plugin_loader
        return render(request, 'request_available.html', {
            'is_admin': check_admin(request.user),
            'request_type_list': [
                rt for rt in plugin_loader.request_types if rt.request_visible
            ]
        })


class RequestDetailView(LoginRequiredMixin, View):
    """Allows review of requests by admins as well as the user who
    submitted the request. The submitting user may confirm their
    request, publishing it to the list so admins can review it, or
    cancel it, deleting the request components. Admins may Approve,
    Deny, or mark the request as approved Pending review. They may also
    make minor alterations to fix typos. Interactions with the request
    after it is confirmed will be recorded and reported.
    """
    def get(self, request, pk):
        from .models import plugin_loader
        req = get_object_or_404(Request, pk=pk)
        is_admin = check_admin(request.user)

        # Only an admin or the requester should be able to review a Request
        if req.requester != request.user.username and not is_admin:
            return HttpResponseForbidden()

        if is_admin:
            request_log(req, 'VIEW - {0}'.format(request.user))

        widgets = []
        for model in plugin_loader.request_types:
            widgets.extend(model.objects.filter(request=req))

        return render(request, 'request_detail.html', {
            'req'           : req,
            'widgets'       : widgets,
            'history'       : RequestLogEntry.objects.filter(request=req),
            'email_options' : EmailTemplate.objects.all(),
            'is_admin'      : is_admin,
            'is_requester'  : req.requester == request.user.username,
        })

    def post(self, request, pk):
        req = get_object_or_404(Request, pk=pk)
        is_admin = check_admin(request.user)
        action = request.POST.get('action', '')
        next = request.POST.get('next', 
            req.review_url() if is_admin else reverse('user_requests:conclusion')
        )
        request_log(req, '{0} - {1}'.format(action, request.user))
        
        if req.requester != request.user.username and not is_admin:
            return HttpResponseForbidden() # Only an admin or the requester should view
        if not is_admin and action not in ('CONFIRM', 'CANCEL'):
            return HttpResponseForbidden() # The requester can only confirm or cancel
        
        if action == 'CONFIRM':
            req.on_confirmed()
        elif action == 'CANCELLED':
            req.status = action
            req.save()
        elif action == 'UPDATE':
            req.requester = request.POST.get('requester', req.requester)
            req.description = request.POST.get('description', req.description)
            req.notification_id = int(request.POST.get('notification', req.notification))
            req.save()
        elif action == 'PENDING':
            req.on_pending()
        elif action == 'APPROVED':
            req.on_approved()
        elif action == 'DECLINED':
            req.status = action
            req.save()
        elif action == 'PROCESSED':
            req.on_processed()
        
        return redirect(next)


class RequestUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Base class for Updating a request. Should be subclassed for each
    type of request and provide the fields that admins can edit after
    the request has been confirmed.
    """
    model = RequestType

    def test_func(self):
        return check_admin(self.request.user)

    def get(self, request):
        return HttpResponseForbidden() # No GET, only POST

    def form_invalid(self, form):
        return HttpResponseBadRequest()

    def form_valid(self, form):
        request_log(form.instance.request, 'MODIFIED - {0}'.format(self.request.user))
        return super(RequestUpdateView, self).form_valid(form)


class RequestListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    """Displays confirmed requests. Supports pagination and filtering
    based on status and requesting user's name.
    """
    context_object_name = 'requests'
    template_name  = 'request_list.html'
    paginate_by = 25

    def test_func(self):
        return check_admin(self.request.user)

    def get_queryset(self):
        filters = {'confirmed': True}
        for field in ['status', 'requester', 'description__icontains']:
            if field in self.request.GET and self.request.GET.get(field,''):
                filters[field] = self.request.GET[field]
        return Request.objects.filter(**filters).order_by('-submitted')


class RequestConclusionView(TemplateView):
    template_name = 'request_conclusion.html'

user_requests/templates/requests/new_vm/form.html
{% extends "base.html" %}

{% block content %}
<h1 class="text-center">Request a new virtual machine</h1>

<div class="row">
  <div class="col-md-8">
    <p>This form allows you to request that a new Virtual Machine be provisioned on the Homelab.</p>
    <br>
  </div>
</div>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}

    {{ form.non_field_errors.as_p }}

    <div class="row form-group {% if form.name.errors %} has-error{% endif %}">
      <label class="font-weight-bold">Provide a hostname for the Virtual Machine (lowercase letters and numbers, no spaces)
        <span style="color:red;">*</span>
      </label>
      {{ form.name }}
      <strong class="help-block">{{ form.name.errors.as_p }}</strong>
    </div>

    <div class="row form-group {% if form.project.errors %} has-error{% endif %}">
      <label class="font-weight-bold">Select the project to associate with the new Virtual Machine:
        <span style="color:red;">*</span>
      </label>
      {{ form.project }}
      <strong class="help-block">{{ form.project.errors.as_p }}</strong>
    </div>

    <div class="row ">
      
      <div class="col-sm-4 form-group {% if form.cores.errors %} has-error{% endif %}">
        <label class="font-weight-bold">Desired Cores:
          <span style="color:red;">*</span>
        </label>
        {{ form.cores }}
        <strong class="help-block">{{ form.cores.errors.as_p }}</strong>
      </div>
      
      <div class="col-sm-4 form-group {% if form.memgb.errors %} has-error{% endif %}">
        <label class="font-weight-bold">Desired RAM (in GB):
          <span style="color:red;">*</span>
        </label>
        {{ form.memgb }}
        <strong class="help-block">{{ form.memgb.errors.as_p }}</strong>
      </div>
      
      <div class="col-sm-4 form-group {% if form.diskgb.errors %} has-error{% endif %}">
        <label class="font-weight-bold">Desired Disk (in GB):
          <span style="color:red;">*</span>
        </label>
        {{ form.diskgb }}
        <strong class="help-block">{{ form.diskgb.errors.as_p }}</strong>
      </div>

    </div>


    <div class="row form-group {% if form.description.errors %} has-error{% endif %}">
      <label class="font-weight-bold">Describe how the VM will be used, along with any other system requirements:
        <span style="color:red;">*</span>
      </label>
      {{ form.description }}
      <strong class="help-block">{{ form.description.errors.as_p }}</strong>
    </div>

    <div class="row form-group {% if form.packages.errors %} has-error{% endif %}">
      <label class="font-weight-bold">List any packages that you want installed on the system (Unless otherwise negotiated, platform will be CentOS):
      </label>
      {{ form.packages }}
      <strong class="help-block">{{ form.packages.errors.as_p }}</strong>
    </div>

    <div class="row form-group {% if form.privileges.errors %} has-error{% endif %}">
      <label class="font-weight-bold">Describe any administrative privileges you want on the machine (sudoers file syntax preferred, but not necessary):
      </label>
      {{ form.privileges }}
      <strong class="help-block">{{ form.privileges.errors.as_p }}</strong>
    </div>

    <p style="text-align: center; color:red;">
      <strong>* Required field</strong>
    </p>

  <p style="text-align:center;">
    <button class="btn btn-primary" type="submit">Submit Request</button>
  </p>
</form>

{% endblock %}

user_requests/templates/requests/new_vm/review_widget.html
  <div class="card-header">New Virtual Machine Request:</div>
  <div class="card-body">

    <div class="form-group">
      <label class="col-form-label" for="id_name">Name:</label>
      <input class="form-control" id="id_name" name="name" type="text" value="{{ item.name }}">
    </div>

    <div class="form-group">
      <label class="col-form-label" for="id_project">Project:</label>
      <input class="form-control" id="id_project" name="project" type="text" value="{{ item.project }}">
    </div>
    
    <div class="row">
        
      <div class="col-sm-4 form-group">
        <label class="col-form-label" for="id_cores">Cores:</label>
        <input class="form-control" id="id_cores" name="cores" type="text" value="{{ item.cores }}">
      </div>
    
      <div class="col-sm-4 form-group">
        <label class="col-form-label" for="id_memgb">RAM:</label>
        <input class="form-control" id="id_memgb" name="memgb" type="text" value="{{ item.memgb }}">
      </div>
    
      <div class="col-sm-4 form-group">
        <label class="col-form-label" for="id_diskgb">Disk:</label>
        <input class="form-control" id="id_diskgb" name="diskgb" type="text" value="{{ item.diskgb }}">
      </div>

    </div>

    <div class="form-group">
      <label class="col-form-label" for="id_description">Description:</label>
      <textarea class="form-control" id="id_description" name="description">{{ item.description }}</textarea>
    </div>

    <div class="form-group">
      <label class="col-form-label" for="id_packages">packages:</label>
      <textarea class="form-control" id="id_packages" name="packages">{{ item.packages }}</textarea>
    </div>

    <div class="form-group">
      <label class="col-form-label" for="id_privileges">privileges:</label>
      <textarea class="form-control" id="id_privileges" name="privileges">{{ item.privileges }}</textarea>
    </div>

  </div>