accounts/urls.py
from django.urls            import include, path

from .views import Profile

urlpatterns = [
    path("", include('django.contrib.auth.urls')),
    path("profile/",  Profile.as_view(),  name='accounts-profile'),
    path("profile/<username>/",  Profile.as_view(),  name='accounts-profile-byname'),
]

user_requests/urls.py
from django.urls    import path

from .models    import plugin_loader
from .views     import (AvailableRequestsView, RequestConclusionView,
                        RequestDetailView, RequestListView)

app_name = "user_requests"

urlpatterns = [
    path('', AvailableRequestsView.as_view(), name='available'),
    path('list/', RequestListView.as_view(), name='list'),
    path('view/<int:pk>/', RequestDetailView.as_view(), name='review'),
    path('conclusion/', RequestConclusionView.as_view(), name='conclusion'),
] + plugin_loader.urls # Add the URLs for the plugins

userportal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    path(
        'robots.txt',
        TemplateView.as_view(
            template_name="robots.txt", content_type="text/plaintext"
        ), 
        name="robots"
    ),

    path('accounts/',  include('accounts.urls')),
    path('duo/',  include('duo_auth.urls')),
    path('user_requests/',  include('user_requests.urls')),
    path('openacct/',  include('openacct.urls')),
    path('fractalip/',  include('fractalip.urls')),
    path('logins/',  include('admin_toolbelt.contrib.login_records.urls')),
    path('admin/', admin.site.urls),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_requests/models.py
import importlib
import inspect

from django.conf                    import settings
from django.contrib.auth.models     import User
from django.core.mail               import send_mail
from django.db                      import models
from django.template                import Template, Context
from django.urls                    import reverse
from django.utils.module_loading    import import_string


GET_EMAIL_VALUE = getattr(settings, 'USER_REQUESTS_GET_EMAIL',
    lambda u: User.objects.get(username=u).email
)
get_email = (
    GET_EMAIL_VALUE if callable(GET_EMAIL_VALUE) else import_string(GET_EMAIL_VALUE)
)

status_options = (
    ('NEW', 'NEW'),
    ('PENDING', 'PENDING'),
    ('APPROVED', 'APPROVED'),
    ('DECLINED', 'DECLINED'),
    ('PROCESSING', 'PROCESSING'),
    ('PROCESSED', 'PROCESSED'),
    ('FAILED', 'FAILED'),
    ('CANCELLED', 'CANCELLED'),
)


class EmailTemplate(models.Model):
    created         = models.DateTimeField(auto_now_add=True)
    name            = models.CharField(max_length=64)
    default_from    = models.CharField(max_length=64)
    subject         = models.CharField(max_length=64)
    body            = models.TextField()

    def send(self, to, from_email=None, context={}):
        send_mail(
            Template(self.subject).render(Context(context)),
            Template(self.body).render(Context(context)),
            from_email if from_email else self.default_from,
            to,
        )


class Request(models.Model):
    """Common information for all requests, facilitates ListView."""
    submitted       = models.DateTimeField(auto_now_add=True)
    requester       = models.CharField(max_length=32) # request.user.username
    confirmed       = models.BooleanField(blank=True, default=False)
    autoprocess     = models.BooleanField(blank=True, default=True)
    autonotify      = models.BooleanField(blank=True, default=True)
    notification    = models.ForeignKey(
        EmailTemplate, models.SET_DEFAULT, blank=True, null=True, default=1
    )
    description     = models.CharField(max_length=512, blank=True, default="")
    status          = models.CharField(
        max_length=16, choices=status_options, blank=True, default="NEW"
    )

    @classmethod
    def make_from_http_request(cls, request, status='NEW', description=''):
        """Create and save a new request object from an HTTP request."""
        req = cls(requester=request.user.username, status=status, description=description)
        req.save()
        return req

    def review_url(self):
        """Returns the request's review page URL"""
        return reverse('user_requests:review', kwargs={'pk': self.pk})

    def components(self):
        """Returns the components attached to this request"""
        rval = []
        for rt in plugin_loader.request_types:
            rval.extend(rt.objects.filter(request=self))
        return rval

    def on_confirmed(self):
        for comp in self.components():
            comp.on_confirmed()
        self.confirmed = True
        self.save()

    def on_pending(self):
        for comp in self.components():
            comp.on_pending()
        self.status = 'PENDING'
        self.save()

    def on_approved(self):
        for comp in self.components():
            comp.on_approved()

        if self.autoprocess:
            self.on_processed()
        else:
            self.status = 'APPROVED'
            self.save()

    def on_processed(self):
        for comp in self.components():
            comp.on_processed()

        if self.autonotify:
            self.notification.send([get_email(self.requester)], context={'request':self, 'components':self.components()})
        self.status = 'PROCESSED'
        self.save()


class RequestType(models.Model):
    """Abstract Base Class for all Requests"""
    request_visible = True
    request_description = "Set model's request_description to change this text"
    form_view_name = "user_requests:<name>"
    update_view_name = "user_requests:update_<name>"
    widget_template_path = "should_not_exist.html"

    request = models.ForeignKey(Request, on_delete=models.CASCADE)

    @classmethod
    def approved_requests(cls):
        """Get all objects whose request is marked confirmed and approved."""
        return cls.objects.filter(request__status='APPROVED', request__confirmed=True)

    def get_absolute_url(self):
        """Used by the update view to get back to the review page."""
        return self.request.review_url()

    def on_confirmed(self):
        """Abstract method to be defined for a subclass which will be
        called after confirming a request containing this request type.
        """
        pass

    def on_approved(self):
        """Abstract method to be defined for each subclass which will be
        called for each approved request of that type. It is an error to
        not define this method.
        """
        raise NotImplementedError(
            "Subclasses of RequestType must define this method"
        )

    def on_pending(self):
        """Abstract method to be defined for a subclass which will be called
        after a request containing this request type is set to pending.
        """
        pass

    def on_processed(self):
        """Abstract method to be defined for a subclass which will be called
        after a request containing this request type is set to processed.
        """
        pass

    class Meta:
        abstract = True
        app_label = 'user_requests'


class RequestLogEntry(models.Model):
    """Record actions taken by admins on the request."""
    request = models.ForeignKey(Request, on_delete=models.CASCADE)
    logged  = models.DateTimeField(auto_now_add=True)
    text    = models.CharField(max_length=128)

    def __str__(self):
        return '{0} - {1}'.format(self.logged, self.text)


def request_log(request, message):
    RequestLogEntry(request=request, text=message).save()


class RequestPluginLoader():
    def __init__(self):
        self.plugins = list([ 
            importlib.import_module(n) for n in settings.USER_REQUESTS_PLUGINS 
        ])
        self.request_types, self.urls = [], []

        for p in self.plugins:
            self.urls.extend(getattr(p, 'urlpatterns', []))
            self.request_types.extend(getattr(p, 'request_types', []))

plugin_loader = RequestPluginLoader()

user_requests/views.py
from django.conf                    import settings
from django.contrib.auth.mixins     import LoginRequiredMixin, UserPassesTestMixin
from django.http                    import (HttpResponseBadRequest,
                                            HttpResponseForbidden)
from django.shortcuts               import get_object_or_404, redirect, render
from django.urls                    import reverse
from django.utils.module_loading    import import_string
from django.views.generic           import View, ListView, TemplateView
from django.views.generic.edit      import UpdateView

from .models import EmailTemplate, Request, RequestLogEntry, RequestType, request_log


CHECK_ADMIN_VALUE = getattr(settings, 'USER_REQUESTS_CHECK_ADMIN', lambda u: u.is_staff)
check_admin = (
    CHECK_ADMIN_VALUE if callable(CHECK_ADMIN_VALUE) else import_string(CHECK_ADMIN_VALUE)
)


class AvailableRequestsView(LoginRequiredMixin, View):
    """Display the currently available request types"""
    def get(self, request):
        from .models import plugin_loader
        return render(request, 'request_available.html', {
            'is_admin': check_admin(request.user),
            'request_type_list': [
                rt for rt in plugin_loader.request_types if rt.request_visible
            ]
        })


class RequestDetailView(LoginRequiredMixin, View):
    """Allows review of requests by admins as well as the user who
    submitted the request. The submitting user may confirm their
    request, publishing it to the list so admins can review it, or
    cancel it, deleting the request components. Admins may Approve,
    Deny, or mark the request as approved Pending review. They may also
    make minor alterations to fix typos. Interactions with the request
    after it is confirmed will be recorded and reported.
    """
    def get(self, request, pk):
        from .models import plugin_loader
        req = get_object_or_404(Request, pk=pk)
        is_admin = check_admin(request.user)

        # Only an admin or the requester should be able to review a Request
        if req.requester != request.user.username and not is_admin:
            return HttpResponseForbidden()

        if is_admin:
            request_log(req, 'VIEW - {0}'.format(request.user))

        widgets = []
        for model in plugin_loader.request_types:
            widgets.extend(model.objects.filter(request=req))

        return render(request, 'request_detail.html', {
            'req'           : req,
            'widgets'       : widgets,
            'history'       : RequestLogEntry.objects.filter(request=req),
            'email_options' : EmailTemplate.objects.all(),
            'is_admin'      : is_admin,
            'is_requester'  : req.requester == request.user.username,
        })

    def post(self, request, pk):
        req = get_object_or_404(Request, pk=pk)
        is_admin = check_admin(request.user)
        action = request.POST.get('action', '')
        next = request.POST.get('next', 
            req.review_url() if is_admin else reverse('user_requests:conclusion')
        )
        request_log(req, '{0} - {1}'.format(action, request.user))
        
        if req.requester != request.user.username and not is_admin:
            return HttpResponseForbidden() # Only an admin or the requester should view
        if not is_admin and action not in ('CONFIRM', 'CANCEL'):
            return HttpResponseForbidden() # The requester can only confirm or cancel
        
        if action == 'CONFIRM':
            req.on_confirmed()
        elif action == 'CANCELLED':
            req.status = action
            req.save()
        elif action == 'UPDATE':
            req.requester = request.POST.get('requester', req.requester)
            req.description = request.POST.get('description', req.description)
            req.notification_id = int(request.POST.get('notification', req.notification))
            req.save()
        elif action == 'PENDING':
            req.on_pending()
        elif action == 'APPROVED':
            req.on_approved()
        elif action == 'DECLINED':
            req.status = action
            req.save()
        elif action == 'PROCESSED':
            req.on_processed()
        
        return redirect(next)


class RequestUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Base class for Updating a request. Should be subclassed for each
    type of request and provide the fields that admins can edit after
    the request has been confirmed.
    """
    model = RequestType

    def test_func(self):
        return check_admin(self.request.user)

    def get(self, request):
        return HttpResponseForbidden() # No GET, only POST

    def form_invalid(self, form):
        return HttpResponseBadRequest()

    def form_valid(self, form):
        request_log(form.instance.request, 'MODIFIED - {0}'.format(self.request.user))
        return super(RequestUpdateView, self).form_valid(form)


class RequestListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    """Displays confirmed requests. Supports pagination and filtering
    based on status and requesting user's name.
    """
    context_object_name = 'requests'
    template_name  = 'request_list.html'
    paginate_by = 25

    def test_func(self):
        return check_admin(self.request.user)

    def get_queryset(self):
        filters = {'confirmed': True}
        for field in ['status', 'requester', 'description__icontains']:
            if field in self.request.GET and self.request.GET.get(field,''):
                filters[field] = self.request.GET[field]
        return Request.objects.filter(**filters).order_by('-submitted')


class RequestConclusionView(TemplateView):
    template_name = 'request_conclusion.html'

user_requests/templates/request_available.html
{% extends "base.html" %}

{% block content %}

<p class="lead" style="text-align:center;">Select the type of request you'd like to make:</p>

{% for rt in request_type_list %}
  <div class="row">
    <div class="col-md-12">
      <p style="text-align:center;">
        <a class="btn btn-outline-primary" style="width:50%" href="{% url rt.form_view_name %}">{{ rt.request_description }}</a>
      </p>
    </div>
  </div>
{% endfor %}

<p style="text-align:center;">
  <a style="color:white;" class="btn btn-primary" href="/profile/">Back to Profile</a>
</p>
{% endblock %}

user_requests/templates/request_conclusion.html
{% extends "base.html" %}

{% block content %}

<div class="row justify-content-center">
  <div class="col-md-6">

    <div class="card">
      <div class="card-body">
      {% if message %}
        <p class="lead">{{ message }}</p>
      {% else %}
        <p class="lead">Your request has been submitted. You will receive a
        confirmation email once your request has been processed.
        </p>
      {% endif %}
      </div>
    </div>

    <p style="text-align:center;">
      <a href="{% url "user_requests:available" %}">Back to Requests</a>
    </p>

  </div>
</div>

{% endblock %}

user_requests/templates/request_detail.html
{% extends "base.html" %}

{% block head %}
<script>
function doSubmit(value) {
    document.getElementById("id_action").value = value;
    if (value == "UPDATE") {
        document.getElementById("id_requester").value = document.getElementById("id_requ").value;
        document.getElementById("id_description").value = document.getElementById("id_desc").value;
        document.getElementById("id_notification").value = document.getElementById("id_email_opts").value;
    }
    document.getElementById("action_form").submit();
}
{% if not is_admin %}
window.onload = function(e) {
    $(".form-control").attr("readonly", true);
}
{% endif %}
</script>
{% endblock %}

{% block content %}
<p class="lead">Request {{ req.pk }}:</p>

<div class="row justify-content-sm-center">
  <div class="col-sm-10">
  {% for element in widgets %}
    <form action="{% url element.update_view_name element.pk %}" method=post>
      {% csrf_token %}
      <div class="card">
        {% include element.widget_template_path with item=element is_admin=is_admin widgets=widgets only %}
      
        {% if is_admin %}
        <p style="text-align:center;">
            <button class="btn btn-success" type=submit>Commit Changes</button>
        </p>
        {% endif %}
      </div>
      <br>
    </form>
  {% endfor %}
  </div>
</div>

{% if is_admin and req.confirmed %}
  <div class="row justify-content-sm-center">
    <div class="col-sm-10">
      <div class="card">
        <div class="card-header">Request Details:</div>
        <div class="card-body">
          <div class="form-group">
            <label class="col-form-label" for="id_requ">Requester</label>
            <input type="text" class="form-control" id="id_requ" name="requ" value="{{ req.requester }}">
          </div>
          <div class="form-group">
            <label class="col-form-label" for="id_desc">Description</label>
            <input type="text" class="form-control col-sm-auto" id="id_desc" name="desc" value="{{ req.description }}">
          </div>
          <div class="form-group">
            <label for="id_email_opts">Email Template</label>
            <select class="form-control" id="id_email_opts" name="email_opts">
            {% for opt in email_options %}
              <option value={{ opt.pk }} {% if opt == req.notification %}selected{% endif %}>{{ opt.name }}</option>
            {% endfor %}
            </select>
          </div>
          <p style="text-align:center;">
            <button class="btn btn-success" type="button" onclick="doSubmit('UPDATE')">Update Details</button>
          </p>
        </div>
      </div>
    </div>
  </div>
  <br>

  {% if req.status == "NEW" or req.status == "PENDING" %}
    <p style="text-align:center;">
      <button class="btn btn-success" type="button" onclick="doSubmit('APPROVED')">Approve</button>
      {% if req.status != "PENDING" %}
        <button class="btn btn-warning" type="button" onclick="doSubmit('PENDING')">Approval Wait</button>
      {% endif %}
      <button class="btn btn-danger" type="button" onclick="doSubmit('DECLINED')">Decline</button>
    </p>
  {% elif req.status == "APPROVED" %}
    <p style="text-align:center;">
      <button class="btn btn-primary" type="button" onclick="doSubmit('PROCESSED')">Mark As Manually Processed</button>
    </p>
  {% elif req.status == "FAILED" %}
    <p style="text-align:center;">
      <button class="btn btn-primary" type="button" onclick="doSubmit('APPROVED')">Reattempt Failed</button>
    </p>
  {% endif %}
  
  <ul class="list-group">
  {% for entry in history %}
    <li class="list-group-item">
      {{ entry }}
    </li>
  {% endfor %}
  </ul>
  <br>
  <p style="text-align:center;">
    <a class="btn btn-outline-primary" href="{% url 'user_requests:list' %}">Back to Request List</a>
  </p>
{% endif %}

{% if is_requester and not req.confirmed %}
  <p style="text-align:center;">
    <button class="btn btn-primary" type="button" onclick="doSubmit('CONFIRM')">Confirm and Submit</button>
    <button class="btn btn-danger" type="button" onclick="doSubmit('CANCEL')">Cancel Request</button>
  </p>
{% endif %}


<form id="action_form" method="post">
  {% csrf_token %}
  <input id="id_action" type="hidden" name="action" value="">
  <input id="id_requester" type="hidden" name="requester" value="">
  <input id="id_description" type="hidden" name="description" value="">
  <input id="id_notification" type="hidden" name="notification" value="">
  {% if next %}<input id="id_next" type="hidden" name="next" value="{{ next }}">{% endif %}
</form>

{% endblock %}

user_requests/templates/request_list.html
{% extends "base.html" %}

{% block content %}

<div class="row">
  <div class="col-sm-2">
    <p class="lead">Submitted Requests</p>
  </div>
  <div class="col-sm-10" style="padding-right:1em">
    <form class="form-inline" style="text-align:right" method="get">
      <div class="form-group mr-2">
        <label for="id_requester">Requester:</label>
        <input type="text" class="form-control" id="id_requester" name="requester" placeholder="username">
      </div>
      <div class="form-group mr-2">
        <label for="id_desc">Description:</label>
        <input type="text" class="form-control" id="id_desc" name="description__icontains" placeholder="description">
      </div>
      <div class="form-group mr-2">
        <label for="id_status">Status:</label>
        <select class="form-control" id="id_status" name="status">
          <option selected></option>
          <option>NEW</option>
          <option>PENDING</option>
          <option>APPROVED</option>
          <option>DECLINED</option>
          <option>PROCESSING</option>
          <option>PROCESSED</option>
          <option>FAILED</option>
        </select>
      </div>
      <button type="submit" class="btn btn-primary">Filter</button>
      <a class="btn btn-default" href="{% url "user_requests:list" %}">Reset Filters</a>
    </form>
  </div>
</div>

<br>

<table class="table table-striped">
  <thead>
    <tr>
      <th style="text-align:center;">Status</th>
      <th>Request ID</th>
      <th>Submitted Date</th>
      <th>Requesting User</th>
      <th>Request Description</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  {% for req in requests %}
    <tr>
      <td>  
        <p style="text-align:center;">
          <span class="badge">{{ req.status }}</span>
        </p>
      </td>
      <td>
        <p style="text-align:right">{{ req.pk }}</p>
      </td>
      <td>
        {{ req.submitted }}
      </td>
      <td>
        {{ req.requester }}
      </td>
      <td>
        {{ req.description|default:"" }}
      </td>
      <td>
        <p style="text-align:center;">
          <a href="{{ req.review_url }}" class="btn btn-info">View</a>
        </p>
      </td>
    </div>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% if is_paginated %}
<ul class="pagination">
  {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
  {% else %}
    <li class="disabled"><span>&laquo;</span></li>
  {% endif %}       
  {% for i in paginator.page_range %}
    {% if page_obj.number == i %}
      <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}                            
      <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}                                         
  {% endfor %}                                                
  {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
  {% else %}                                                                
    <li class="disabled"><span>&raquo;</span></li>                              
  {% endif %}                                                                         
</ul>
{% endif %}

{% endblock %}